/**
 * Unicode general-category tables for I-Regexp `\p{...}` and `\P{...}`, generated from
 * Unicode 16.0.
 *
 * GENERATED FILE — do not edit by hand. Regenerate with `npm run gen:unicode`.
 *
 * This file lives inside `regex/` rather than beside the identifier tables in `unicode/` because
 * the I-Regexp engine is a leaf: it names no TSON type and imports nothing outside itself, which
 * is what lets it be used and tested on its own. The decoder below is therefore a second copy of
 * the one in `unicode/xid.ts`; the generator emits both and is what keeps them identical.
 *
 * Only the 29 two-letter categories are stored. Each one-letter category is exactly the union of
 * its members — verified against the host at generation time, not assumed — so `\p{L}` is
 * answered by asking the five letter categories rather than by a 677-range table that could
 * disagree with the parts it is made of.
 */

/** The Unicode version these tables were derived from. */
export const UNICODE_VERSION = '16.0';

const BASE64_ALPHABET = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';

/**
 * Decodes a base64 string to bytes without `atob` or `Buffer`.
 *
 * The package declares no ambient host globals beyond what it already needs, and this runs in both
 * Node and browsers, so the decode is spelled out rather than delegated.
 */
function fromBase64(text: string): Uint8Array {
  const lookup = new Int16Array(128).fill(-1);
  for (let i = 0; i < BASE64_ALPHABET.length; i++) {
    lookup[BASE64_ALPHABET.charCodeAt(i)] = i;
  }

  // A character outside the alphabet reads as -1, which is also what an out-of-range index
  // yields here. Padding is the only such character these tables contain.
  const sextet = (index: number): number => lookup[text.charCodeAt(index)] ?? -1;

  let padding = 0;
  while (padding < 2 && text.charCodeAt(text.length - 1 - padding) === 0x3d /* '=' */) padding++;

  const bytes = new Uint8Array((text.length >> 2) * 3 - padding);
  let out = 0;
  for (let i = 0; i < text.length; i += 4) {
    const a = sextet(i);
    const b = sextet(i + 1);
    const c = sextet(i + 2);
    const d = sextet(i + 3);
    const chunk = (a << 18) | (b << 12) | ((c < 0 ? 0 : c) << 6) | (d < 0 ? 0 : d);
    if (out < bytes.length) bytes[out++] = (chunk >> 16) & 0xff;
    if (out < bytes.length) bytes[out++] = (chunk >> 8) & 0xff;
    if (out < bytes.length) bytes[out++] = chunk & 0xff;
  }
  return bytes;
}

/** Expands a delta-varint encoded table into a flat array of inclusive `[start, end]` pairs. */
function decodeTable(encoded: string): Uint32Array {
  const bytes = fromBase64(encoded);
  const bounds: number[] = [];
  let i = 0;
  let previousEnd = -1;

  // Running off the end of a well-formed table is impossible; treating it as a terminator rather
  // than asserting keeps the decode total, so a truncated table yields a short table instead of a
  // crash at module load.
  const readVarint = (): number => {
    let result = 0;
    let shift = 0;
    for (;;) {
      const byte = bytes[i++];
      if (byte === undefined) return result >>> 0;
      result |= (byte & 0x7f) << shift;
      if ((byte & 0x80) === 0) return result >>> 0;
      shift += 7;
    }
  };

  while (i < bytes.length) {
    const gap = readVarint();
    const width = readVarint();
    const start = previousEnd + 1 + gap;
    const end = start + width;
    bounds.push(start, end);
    previousEnd = end;
  }

  return Uint32Array.from(bounds);
}

/** Binary search over a flat `[start, end, start, end, ...]` array of inclusive ranges. */
function contains(table: Uint32Array, codePoint: number): boolean {
  let low = 0;
  let high = (table.length >> 1) - 1;
  while (low <= high) {
    const mid = (low + high) >> 1;
    const start = table[mid << 1];
    const end = table[(mid << 1) + 1];
    // Both indices are in bounds for any table this module decodes; the guard is what lets the
    // reads stay unasserted, and a missing bound can only mean "not in the table".
    if (start === undefined || end === undefined) return false;

    if (codePoint < start) {
      high = mid - 1;
    } else if (codePoint > end) {
      low = mid + 1;
    } else {
      return true;
    }
  }
  return false;
}

/** Lu: 651 ranges, 1325 bytes encoded. */
const GC_LU = /* @__PURE__ */ decodeTable(
  'QRllFgEGIQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQACAAEAAQABAAEAAQABAAEAAgABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEBAQABAAMBAQABAQECAgMBAQECAwEBAQEAAQABAQEAAgABAQECAQABAQMABwACAAIAAgABAAEAAQABAAEAAQABAAIAAQABAAEAAQABAAEAAQABAAIAAgABAgEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQAHAQEBAgABAwEAAQABAAEAoQIAAQADAAgABgABAgEAAQEBEAEIIwACAgMAAQABAAEAAQABAAEAAQABAAEAAQABAAUAAgABAQIyMAABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAkAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEBAQABAAEAAQABAAEAAgABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAiXJFiUBAAUA0gVVkxEABioCAsACAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQAJAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAkHCAUKBwgHCAULAAEAAQABAAgHSAMMAwwDDAQLA4YCAAQAAwICAgIAAwQGAAEAAQABAwIDCgEFAD0A/BQvMAABAgIAAQABAAEDAQACAAgCAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQAIAAEABADN8gEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQATAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAhwEAAQABAAEAAQABAAEAAwABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQAKAAEAAQEBAAEAAQABAAQAAQACAAEAAwABAAEAAQABAAEAAQABAAEAAQABBAEEAQABAAEAAQABAAEAAQABAwEAAQEDAAUAAQABAAEAGACrrgEZxQkniAEjnAEKAQ4BBgEB6g0ynQEVuhYfgKsBH6DLARkaGRoZGgABAQIAAgECAwEHGhkaAQEDAgcBBhsBAQMBBAEAAwYbGRoZGhkaGRoZGhkeGCEYIRghGCEYIQC1IiE=',
);

/** Ll: 662 ranges, 1348 bytes encoded. */
const GC_LL = /* @__PURE__ */ decodeTable(
  'YRk6ACkXAQcBAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAQEAAQABAAEAAQABAAEAAQEBAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAgABAAECAgABAAIAAwEEAAIAAwICAAIAAQABAAIAAQEBAAIAAwABAAIBAgIGAAIAAgABAAEAAQABAAEAAQABAAEBAQABAAEAAQABAAEAAQABAAEBAgABAAMAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABBgIAAgEBAAQAAQABAAEAAUQBGsEBAAEAAwADAhIAGyIBAQMCAQABAAEAAQABAAEAAQABAAEAAQABAAEEAQACAAIBMy8BAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEACQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAgABAAEAAQABAAEAAQEBAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQAwKMcWKgIC+AUFghEIAQB1Kz8MASFmAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQgBAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABCAgFCgcIBwgFCgcIBwgNAgcIBwgHCAQBAQYAAwIBAQgDAgEIBwoCAQGSAgADAQMAGwAEAAQAAgEIAwQANQCrFS8BAAMBAQABAAEABAABAQEFBQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAQcAAQAEAAwlAQAFAJPyAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABABMAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQCHAQABAAEAAQABAAEAAQIBAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEHAQABAAIAAQABAAEAAQAEAAEAAgABAgEAAQABAAEAAQABAAEAAQABAAEABQAFAAEAAQABAAEAAQABAAEABAABAAIAAwABAAEAAQABAAEAGgADALUGKgUIB0/AngEGDASpCBnNCSeIASObAQoBDgEGAQGDDjJ9FboWH4CrAR+aywEZGgYBERoZGgMBAAEGAQoaGRoZGhkaGRoZGhkaGRoZGhscGAEFGhgBBRoYAQUaGAEFGhgBBQEAtA4JARMGBfcTIQ==',
);

/** Lt: 10 ranges, 22 bytes encoded. */
const GC_LT = /* @__PURE__ */ decodeTable('xQMAAgACACYAlTsHCAcIBwwADwAvAA==');

/** Lm: 75 ranges, 189 bytes encoded. */
const GC_LM = /* @__PURE__ */ decodeTable(
  'sAURBAsOBAcAAQCFAQAFAN4DAOYBAKQBAY0CAQQAHwAJAAMAoAEApwEA1AkAfwC1BADaDQBrAOMEANADBa4BPg0AIiSxBQANABAM3xcB8QEAvwEA1QMAKwQFAGEBXQKW3gEA4gkFjgIAcgAcAXkIUAAXAGkCAwHVAwAWAIkBAGwAFQFnAwkAhqgBAC0B4A8FASkBCJMLACAA0LsBA/wDAigBpgQMQAEBAIyAAQMBBgEBsWA9yQEGrQcA3wgA',
);

/** Lo: 528 ranges, 1130 bytes encoded. */
const GC_LO = /* @__PURE__ */ decodeTable(
  'qgEADwCAAgAEA9ABALsGGgQDLR8BCSMBAWIBABgBCgICABAAAR0dWAsAGCAVFSoYBwoFFwEFESg7NQMAEgAHCRAOBAcCAQIVAQYBAAMDAwAQAA0BAQIOAQoACAUEAQIVAQYBAQEBAQEfAwEAEwIQCAECARUBBgEBAQQDABIADwEXAAsHAgECFQEGAQEBBAMAHgEBAg8AEQABBQMCAQMDAQEAAQEDAQMCAwsWADQHAQIBFgEPAwAaAgIAAgEeAAQHAQIBFgEJAQQDAB8BAQEPAREIAQIBKAIAEAAFAggCGAUFEQMXAQgBAAIGOi8BAQwFOwEBAAEEARcBAAEJAQEJAAIEFwMgAD8HASMbBHMqFAAQBQQDAwADAQcCBAwMAHHIAgEDAgYBAAEDAigBAwIgAQMCBgEAAQMCDgE4AQMCQiUPcesEAhABGQVKBgcHEQ0SDhEODAECDzMoAEMiATQHBAIhAQAFRQoeMR0CBAsrBBk2Fgk0sAEuEQc2HQ0BCisaIykCCh1xAwEFAQEDALoIA/cXNxgWCQYBBgEGAQYBBgEGAQYBBqcEADUABFUIAAFZBAAFKgFdER8wD4AEvzNAlKQBAfYIQycIiwIEDwoBQgAxRakBAGcAAwYBAgEDARYdMw4xPgUDAAEBCxsKFhkcBy4tBAIICgQBKBcCAQcUDwEFAwADMQEAAwECBAIAAQAYAQMKBwAOBQIFAgUJBgEGkQEiHaNXDBYEMIRC7QICaUMAAQkBDAEEAQABAQEBAWsh6gISPwI1KAt0BAGGAWkJASwCHgMFAgUCBQICIwsBGQESAQEBDgINInqFAxwDMC8fDRMBBwYlCh0CIwQHgAFNYicIM1wzDLYCCRUKB5gBBQIAASsBAQMAAhYKFgkeQRIBAQoVChlGNwYBQAAPAwECARwqHAMcIwcBGxs1ChUKEg0Rbki3ASMmAwEAsAIpBgEQAjscCgAIFSoRLhQbFgw0OQECAA0sIBgaIx0AAgAIIgMADC8OAxUAAQAjEQEYEwE/BgEAAQMBDgEJBy4mBwIBAhUBBgEBAQQDABIADAQeCQEAAgABJQEAGQABACw0EgMUAh4vFAEBALgBLikDJC8UADsqDQBHGiUGuQEr0wEHAgACBwEBARcPAAEAXgcCJhAAAQAcAAonBwAVAAstEwASSMcBIB8IASQRADEdcAYBAQElFQAZBQEBAR8OAMcCEg8AAQwBIXwAT5kH5gHDAcwUYA+vCBEFGZofBcYEuTUd4g24BAceEU4RHRIvMxQFErMDJ5UDSgUArwH3LwjVCSkJ90WiAg8AHQICAA4DCIsDhBJqBQwDCAcJ8EQA9QMsIQDBAh0SK+QDGuUBHQIA7wMGAQMBAQEOAcQBuwoDARoBAQEAAgABCQEDAQABAAYABAABAAEAAQIBAQEAAgABAAEAAQABAAEBAQACAwEGAQMBAwEAAQkBEAUCAQQBEMQi380CILkgBt0BAoEtDrA6D+0EohOdBOILyiYF3yA=',
);

/** Mn: 357 ranges, 767 bytes encoded. */
const GC_MN = /* @__PURE__ */ decodeTable(
  'gAZvkwIEiQIsAQABAQEBAQBICjAUEABlBgIFAgEBAyMAHhpbCjoICQAYAwEIAQIBBCsCOwgqFwEfNwABAAQHBAADBgoBHQA6AAQDCAAUARoAAgE5AAQBBAECAgMAHgEDAAsBOQAEBAEBBAAUARYFAQA6AAIAAQMIAAcBCwEeAD0ADAAyAAMANwABAgUCAQMHAQsBHQA6AAIABgAFARQBHAE5AQQDCAAUAR0ASAAHAgEAWgACBgwHYgACCAsGSQEbAAEAAQA3DQEEAQEFCgEjCQBmAwEFAQECARkBBAIQAw0AAgEGAA8AvwUCsgcCHQEeAR4BQAEBBggAAgoJAC0CAQB1ASIAdgIEAQkABgLbAQECADoAAQYBAAEAAgcGCQIAMA0BDzEDMAABBAEABQAoCAwBIAMCAQECOAABAQMAAQI6BwIBmAECAQwBBgQABgADAcYBP9AFDAQAAwv+FwKNAQBgH6oEA2sB1OsBAAQJIAFQAZACAAMABAAZAQUAlwEBGhENACYHGQouAjAAAgMCAScAQwUCAQIBDAAIAC8AMwABAgIBBQEBACoBCADuAQACAAQAsJ4BAOEFDxAPzQcA4gEAlQEEhg0CAQEFAygCBAClAQG9BANBBL0CAU8DRgoxA3sANg4pAAIBCgIxAwIBBwA9AiQEAQc+AAwBNAgKAwIAXwICAAEBBgACAJ0BAAMHFQE5AQMAJQYDBEYFDQABAAEADgFVBwICAQAXAFQFAQAEAQEB7gEDBgEBARsBVQcCAAEBagABAAIFAQBlAAEAAgMBBIMCCAEBgAIBAQAEAJABAwIBBAAgCSgFAgMIAAkFAgIuDAEBlgMGAQUBAFIVAgYBAQEBegUDAAEBAQYBAEgBAwABANsCAQsBNAQFAAEAFwDlKQAGDshZCwMCwBMEOwaYCAA/A1EAuJkBAeEkLQIWoAQCEQcCBh4DlAECuw82BDEIAA4AFgQBDtAKBgEQAgYBAQEEZACgAQb3AgA9A/wDA/4BAeAFBm0Gta8w7wE=',
);

/** Mc: 190 ranges, 409 bytes encoded. */
const GC_MC = /* @__PURE__ */ decodeTable(
  'gxIANwACAggDAQEyAToCBgECAQoAKwA6AkIAOgIIAAEBNQE6AAEABgECAQoAZgEBAQMCAQIKACkCPQM9AToAAQQCAQEBCQEcAA4BOgIFAgECCgAqAUsCBgcSAcoCAT8AqwEBBAAGAAIBGQEKAgIGFQECBQIACgL4DAAeAIEBAAcHAQHaAgMCAgQBAQXgAQE6AAEACQABAQgFkQEAMAAFAAEEAQE9AB4ABAECADwAAgIBAAMBMAcIAasBABUAtiYB8+8BAQIAWAEyD44BAS8AMAEEAQICbgECARgALQABAG0AAgEFAO0BAQEBAQEBAJPIAQABAH8ALQIEAXMAGAE7ADACCQENAF0CAwEBAKoBAh8BOgEBAwIBAgIJAAoBVAIHAAIAAQMBAQEAZQIIAQMAagIGAAEDAgDtAQIGAwIAcQIIAQEAbQABAQYAZwABAQQAhQICCQD3AQUBAQQAAgABAI4BAggDBABUAB0BPgCXAwAOAGoABwACANUBBAQBAQDeAgEMADABCAEBAOiDAQKkHDZoAfPCAQEGBQ==',
);

/** Me: 5 ranges, 15 bytes encoded. */
const GC_ME = /* @__PURE__ */ decodeTable('iAkBtCwAngwDAQKLiwIC');

/** Nd: 71 ranges, 186 bytes encoded. */
const GC_ND = /* @__PURE__ */ decodeTable(
  'MAmmDAmGAQnGAQmcAwl2CXYJdgl2CXYJdgl2CXYJdglgCXYJRgmWAglGCcYOCSYJrAIJgAEJpgEJBgm2AQlWCYYBCQYJxpMCCaYFCSYJxgEJFglWCZYDCZamAQmGCwmGEQkGCZwGCYABCTwJkAEJlgIJ1gIJdgn2AglmCQYTTAmmAwlmCZYFCVYJ9gEJRgmmAwnWgwEJphIJVgmGAQmWBAn2vgEJ1BUxwBIJpgMJ9gMJ9wEJ1QYJliUJ',
);

/** Nl: 12 ranges, 34 bytes encoded. */
const GC_NL = /* @__PURE__ */ decodeTable('7i0C7xQiAgP+HAAZCA4Cq+0BCdC0ATTMAwAIAIYBBKpAbg==');

/** No: 72 ranges, 184 bytes encoded. */
const GC_NO = /* @__PURE__ */ decodeTable(
  'sgEBBQACArUSBfgCBXgChQEG2QEGEQixAwm1CBPzCAngAwCVDQADBQYJxgEPKQDWBTtOFfYEHekKAJQJA4oBCR4HAQ4gCScO8OoBBdGxASxBAxEB1QIaJAO0CgcZBicISwQWBaABAQIPAi1ACDQBHgJLBGgHGAcpBsoCBeACHp4BCSoDcAaGARP7AhPFCgGuAwjnBhLTBhSGlwEGngYWqcgBEwwTbBjOKgihBzoBAgEDTCwBDsIHDA==',
);

/** Pc: 6 ranges, 16 bytes encoded. */
const GC_PC = /* @__PURE__ */ decodeTable('XwDfPwETAN67AwEYAu8BAA==');

/** Pd: 20 ranges, 51 bytes encoded. */
const GC_PD = /* @__PURE__ */ decodeTable(
  'LQDcCgAzAMEcAIUIAIkQBYEcAAIAHwEEABwAvgMAEwBvAJCbAwElAAoAqQEA4BwAvgIA',
);

/** Ps: 79 ranges, 170 bytes encoded. */
const GC_PS = /* @__PURE__ */ decodeTable(
  'KAAyAB8Avh0AAQDeDgD+EgADACYANwAPAPoEAAEAHgC+CAABAAEAAQABAAEAAQBQACAAAQABAAEAAQCUAwABAAEAAQABAAEAAQABAAEAAQABAEAAAQAhAKUIAAEAAQABABkAEgABAAEAAQCsAwABAAEAAQABAAMAAQABAAEAAgChmgMA1wEAHQABAAEAAQABAAEAAQABAAMAEQABAAEAqgEAMgAfAAMAAgA=',
);

/** Pe: 76 ranges, 164 bytes encoded. */
const GC_PE = /* @__PURE__ */ decodeTable(
  'KQAzAB8AvR0AAQDeDgCpEwA3AA8A+gQAAQAeAL4IAAEAAQABAAEAAQABAFAAIAABAAEAAQABAJQDAAEAAQABAAEAAQABAAEAAQABAAEAQAABACEApQgAAQABAAEALAABAAEAAQCsAwABAAEAAQABAAMAAQABAAEAAgGemgMA2QEAHQABAAEAAQABAAEAAQABAAMAEQABAAEAqgEAMwAfAAIAAgA=',
);

/** Pi: 11 ranges, 25 bytes encoded. */
const GC_PI = /* @__PURE__ */ decodeTable('qwEA7D4AAgECABkAyBsAAQAEAAIADwADAA==');

/** Pf: 10 ranges, 23 bytes encoded. */
const GC_PF = /* @__PURE__ */ decodeTable('uwEA3T4AAwAcAMgbAAEABAACAA8AAwA=');

/** Po: 193 ranges, 444 bytes encoded. */
const GC_PO = /* @__PURE__ */ decodeTable(
  'IQIBAgIAAQABAQoBAwEbAEQABQAOAQcAvgUACADSAwUpADYAAgACACwBFAEBAQ0AAQJKA2YAKw3pAQI2Dh8AhQIBCgCMAQB4AHkAhgMADADvAgBaAAoBqAEOAQBwAEoEBAFvBasBAOQECIUGAHwCRwGdAQIBAiUFAQO5AgHYAQGAAQYBBaABAQoGHAJ8AzsEPgFABwsAwgYBCAcICAIDAgIDCgEAAQmaGQMBAXAAjwEBBAICAAIIAQEBAAIBCgQBCQIDAQABDAICrAMCOQC9AQCC6AEBjQICYwAKAHMF/AIDVgEoAgEAMQEvAGEMEAF8A34BEAH5AQCkpAEGAgAWABQBAgMDAgEDBwIGAAEBlQECAQICAAEAAQEKAQMBGwAkAAIBmgMCnAUAMACeAwDnBQDHAQAfAJACCCYAcAZCBlkDuAcELAO9AQZtAQEDfgMwAU8DBAANAAECWAVrAKoCAQEBcgQKAQEAaAD6ARZpAhwMTACCAQL8AQCIAgKbAQBcB1MCAQRdCdcBAF8EKgGFBQFKDK8BAPAIBPwWAft0AYUBAEEECACoBAKnAgPHAgC8mQEA5zsE8xYA3gYB',
);

/** Zs: 7 ranges, 17 bytes encoded. */
const GC_ZS = /* @__PURE__ */ decodeTable('IAB/AN8rAP8SCiQALwCgHwA=');

/** Zl: 1 ranges, 3 bytes encoded. */
const GC_ZL = /* @__PURE__ */ decodeTable('qEAA');

/** Zp: 1 ranges, 3 bytes encoded. */
const GC_ZP = /* @__PURE__ */ decodeTable('qUAA');

/** Sm: 65 ranges, 149 bytes encoded. */
const GC_SM = /* @__PURE__ */ decodeTable(
  'KwAQAj0AAQAtAAQAJQAfAP4FAI8EArs0AA0AJwINAosBACcEBgBEBAUBBAACAAIABwAfAQIAAQAfiwIgAVoAHhgoBdUDAAkANgdvANACBAIeCg+AAoIBFj4EHwKBAjAUAgXcnwMAuAYAAQKkAQAQAj0AAQCDAQAGA6EbAbGSAwAZAB8AGQAfABkAHwAZAB8AGQCsLgE=',
);

/** Sc: 21 ranges, 60 bytes encoded. */
const GC_SC = /* @__PURE__ */ decodeTable(
  'JAB9A+kJAHsA8gMB8gMBBwD1AQCHAgDFBACbEwDEESD3jgIAw6sBAGwAmgEA2wEBAwH2PwOehgMAsBMA',
);

/** Sk: 31 ranges, 75 bytes encoded. */
const GC_SK = /* @__PURE__ */ decodeTable(
  'XgABAEcABgAEAAMAiQQDDA0FBgEAARB1AA4BggoAtC4AAQILAg0CDQINAZwhAePsARYJAWcB0AcADgHGoAEQ+wYAAQCiAQCX6AME',
);

/** So: 187 ranges, 438 bytes encoded. */
const GC_SO = /* @__PURE__ */ decodeTable(
  'pgEAAgAEAAEA0QcAigIBfwHOAQAKABMB9wEAgwQA9QIAggEFAQCEAQDPAQApAIcDAg8AAQICBRQAAQABAIUBBwEFAQEFA8UBAfAFCdMFANIFAJ0BIeECCQkIgwsBAQMBAQoAAQEGBQEAAQABAAQACwEOAAEBAQA6AQkEAgMBAQEBAQYBHgIBAQABHowCBwQTAgYCUAEdGScGRxYKUU0WtgEBCAE1CG4B9wEsK0D/AYAELxUBBiYCHwFo5QEF5QIBLhkBWAzVARoPBAANAQwAFQEGAdACAQQJICUJABAeCx0IAA8fCiYPvwLAMz+QrQE24QYDCgEBAL0EAsalAQ9/AC0C5AMAAwAEAQ0BuQIIORACAgEMAwAvLPoMAc8EAPYYAJURBwQQypYBAwUA1qIBAOMe7wEQswOcAXM89QEKJgI7BQIWAQcdBDwVQQMAugFWqQn/AzcDMgcBDQEByA0A3BYAgQEA0QUrBGMMDgIOAQ4BJBegATgcDSsECAcBDgWaAfoBBdcFBBADDAN2BF4GCwQADwsENwgJBicIHQILBAE+0wIMDQIMAwkFNwcOAgoGCAeSAQFb',
);

/** Cc: 2 ranges, 4 bytes encoded. */
const GC_CC = /* @__PURE__ */ decodeTable('AB9fIA==');

/** Cf: 21 ranges, 58 bytes encoded. */
const GC_CF = /* @__PURE__ */ decodeTable(
  'rQEA0goFFgDAAQAxAIADAVAAqx4A/A8EGgQxBAEJj70DAPkBAsEhAA8A4kYP4JACA88pB4bdMAAeXw==',
);

/** Cn: 731 ranges, 1558 bytes encoded. */
const GC_CN = /* @__PURE__ */ decodeTable(
  '+AYBBgMHAAEAFACNAwAmATIBAwA3BxsDBgqOAgA8AWUNOwExAQ8AHAEBAAsEHwACBO0BAAgBAgEWAAcAAQIEAQkBAgEEBwEDAgAFARkBAwAGAwIBFgAHAAIAAgACAQEABQMCAQMCAQYEAAEGEQkDAAkAAwAWAAcAAgAFAQoAAwADAQEOBAEMBgcAAwAIAQIBFgAHAAIABQEJAQIBAwYDAwIABQESCQIABgIDAAQCAgABAAICAgIDAgwDBQIDAAQBAQUBDRUEDQADABcAEAEJAAMABAYCAAMBAQEEAQoGFgADABcACgAFAQkAAwAEBgIFAgAEAQoAAwsNAAMAMwADAAYDEAEaAAMAEgIYAAkAAQEHAgEDBgABAAgFCgEDCzoDHSQCAAEABQAYAAEAFwEFAAEABwAKAQQfSAAkAycAJAAPAA0kxgEAAQQBAfkCAAQBBwABAAQBKQAEASEABAEHAAEABAEPADkABAFDASACGgVWAQYBnQUCWQYWCBgIFAsNAAMAAgteAQoFCgUaBVkGKwRGCR8ADAMMAwECKgEFCiwDGgULAj4BQQAdAQsFCgUOAR8wTQCmAQc8Ag8CPgQrAQsHKwSWBAEGASYBBgEIAAEAAQABAB8BNQAPAA4BBgATAQMACQBlAAwBGwANAiEOIQ6MAQOaBRULFJQOASAA3QIELQABBAEBOAYCDRgIBwAHAAcABwAHAAcABwAHAH4hGgBZC9YBGVAAVgFnBCsAXgBWCDAA7eQBAjcI3AITuAEHzgEBAgABAAgUOwIKBTgHRgcMBXQKHgJOAAsDIQA3CA4BCgFnFxwJBgEGAQYIBwAHADwDfgEKBaRXCxcDMYMQ7jQBaiUHCwUEGgAFAAEAAgACAH0PvQMBNgYBHyoFMwATAAQDBQCHAQEBAL4BAgYBBgEGAQMCBwAHCQUBDAAaABMAAgAPAQ4hewQDAy0CWAANAgEuLoEBHQIxDhwDJAgeBCsEHgAlAw4pngEBCgUkAyQDKAc0CgwADwAHAAIACwAPAAcAAgI0C7cCCBYJCBcGACoACUQGAQEALAACAgEBFwBIBwkvEwACBCECGwQBPzgDFAEyAAIECAADAB0BAwMKBgkGQB8nAwwINgIdARsEGgYECwdPSTYzDDMGLgcKBSYCHQcCzwEfACoAAwECDwM2LAcqFRolHBMXCE4DJAhECQEBGQYKBTUAEgcnCGAAFAoSAC89BwABAAQADwALBTsECgUEAAgBAgEWAAcAAgAFAAoBAgEDAQEFAQQHAQcCBQoKAAEBAQAmAAoAAQEBAAQACgACBwIcXAAFHUgHCqUBNgEmIUUKCgUNEjoFCgUUGxsBDwMXuAE8Y1MLCAEBAQgAAgAeAAIBDAgKRQgBLgELGkgHUwxJBgq1ASINCgUJAC0ADgkdAiABFgAOSAcAAgAsAgEAAgAJBwoFBgACACUAAgAGBgq1AhkGEQApAh1UAQ4yDJsHZW8ABQrEAcsUYwzWCAmbHwTHBLg1OsUNuQQGHwAKA1EACgUeAQYJRgkKAAcAFQQTrwM6xQFbZEsDOQYRPwUKAg34LwfWCSgK5kUEAAcAAgCjAg4BHAMBAQ0EB4wDgxJrBA0CCQYKAQjbHvoBBbQDSy4BFwh0O/YBCScBwgEURnkUCxQLVwgZhgFVAEcAAgEBAQIBBAAMAAEABwBBAAQBCAAHABwABAAFAAECBwDUAgGkAgG+BQ4FAA/PCB8FBtQBBwARAQcAAgAFBD4gAW8tAg4BCgMCvwIfEDoEAc8DKtUBKwMB3wMHAAQAAgAPAMUBARAoTAMKAwKQBkRLPcEBBAAbAAIAAQEBAAoABAABAAEFAQMBAAEAAQADAAIAAQEBAAEAAQABAAEAAgABAQQABwAEAAQAAQAKABEEAwAFABEzAo0CLANkCw8BDwAPACUJrgE3HQwsAwkGAg0GmQHYBwMRAg0CdwNfBQwDAQ4MAzgHCgUoBx4BDAMCPdQCCw4BDQIKBDgGDwELBQkGkwEAZoUI4M0CH7ogBd4BAYItDbE6Du4EoROeBOELyyYE4CDQuCsBHWB/8AGP/AP+/wMB/v8DAQ==',
);

/** Co: 3 ranges, 15 bytes encoded. */
const GC_CO = /* @__PURE__ */ decodeTable('gMAD/zGAjjj9/wMC/f8D');

/** The two-letter general categories, each backed by its own table. */
const LEAF_TABLES: Readonly<Record<string, Uint32Array>> = {
  Lu: GC_LU,
  Ll: GC_LL,
  Lt: GC_LT,
  Lm: GC_LM,
  Lo: GC_LO,
  Mn: GC_MN,
  Mc: GC_MC,
  Me: GC_ME,
  Nd: GC_ND,
  Nl: GC_NL,
  No: GC_NO,
  Pc: GC_PC,
  Pd: GC_PD,
  Ps: GC_PS,
  Pe: GC_PE,
  Pi: GC_PI,
  Pf: GC_PF,
  Po: GC_PO,
  Zs: GC_ZS,
  Zl: GC_ZL,
  Zp: GC_ZP,
  Sm: GC_SM,
  Sc: GC_SC,
  Sk: GC_SK,
  So: GC_SO,
  Cc: GC_CC,
  Cf: GC_CF,
  Cn: GC_CN,
  Co: GC_CO,
};

/** The one-letter categories, each the union of its members. */
const GROUPS: Readonly<Record<string, readonly string[]>> = {
  L: ['Lu', 'Ll', 'Lt', 'Lm', 'Lo'],
  M: ['Mn', 'Mc', 'Me'],
  N: ['Nd', 'Nl', 'No'],
  P: ['Pc', 'Pd', 'Ps', 'Pe', 'Pi', 'Pf', 'Po'],
  Z: ['Zs', 'Zl', 'Zp'],
  S: ['Sm', 'Sc', 'Sk', 'So'],
  C: ['Cc', 'Cf', 'Cn', 'Co'],
};

/**
 * Every category name an I-Regexp `\p{...}` escape may name, in the reference implementation's
 * order. A parser should reject anything outside this set rather than treating it as unmatched.
 */
export const CATEGORY_NAMES: readonly string[] = [
  'L',
  'Lu',
  'Ll',
  'Lt',
  'Lm',
  'Lo',
  'M',
  'Mn',
  'Mc',
  'Me',
  'N',
  'Nd',
  'Nl',
  'No',
  'P',
  'Pc',
  'Pd',
  'Ps',
  'Pe',
  'Pi',
  'Pf',
  'Po',
  'Z',
  'Zs',
  'Zl',
  'Zp',
  'S',
  'Sm',
  'Sc',
  'Sk',
  'So',
  'C',
  'Cc',
  'Cf',
  'Cn',
  'Co',
];

const CATEGORY_NAME_SET = /* @__PURE__ */ new Set(CATEGORY_NAMES);

/** Whether `name` is a general category this engine recognises. */
export function isCategoryName(name: string): boolean {
  return CATEGORY_NAME_SET.has(name);
}

/**
 * Whether `codePoint` is in general category `name`.
 *
 * Returns `false` for a name this engine does not recognise; callers that need to reject an
 * unknown category as a syntax error should check {@link isCategoryName} while parsing, where
 * there is a position to report it at.
 */
export function isInCategory(name: string, codePoint: number): boolean {
  const leaf = LEAF_TABLES[name];
  if (leaf !== undefined) return contains(leaf, codePoint);

  const members = GROUPS[name];
  if (members === undefined) return false;

  for (const member of members) {
    const table = LEAF_TABLES[member];
    if (table !== undefined && contains(table, codePoint)) return true;
  }
  return false;
}
