/**
 * `@ltr8/tson/stdlib` — the three bundled schemas, embedded and registered.
 *
 * The point of these is not that the schemas parse (`bundled-schemas-parse.test.ts` and
 * `bundled-schemas-resolve.test.ts` already own that against `spec/m/` directly) but that the
 * *embedded copies* are the same documents, and that registering them produces a `Tson` a caller
 * can immediately resolve a user schema against — which is the whole reason this subpath exists.
 */
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';

import {
  CORE_TN,
  META_KERNEL_TN,
  META_TN,
  registerStandardLibrary,
  standardLibrary,
} from '../src/stdlib/index.js';
import { createTson } from '../src/config.js';

const SPEC_M = join(import.meta.dirname, '../../../spec/m');

describe('the embedded copies are the vendored documents', () => {
  it.each([
    ['meta-kernel.tn', META_KERNEL_TN],
    ['meta.tn', META_TN],
    ['core.tn', CORE_TN],
  ])('%s matches spec/m/ byte for byte', (file, embedded) => {
    // Generated by scripts/gen-stdlib-schemas.mjs. A drift here means the generator was not re-run
    // after the vendored spec moved, and every schema resolved against the embedded copy would be
    // resolved against the wrong revision.
    expect(embedded).toBe(readFileSync(join(SPEC_M, file), 'utf8'));
  });
});

describe('standardLibrary()', () => {
  // Built from the embedded documents' own `!!id` values rather than from a hard-coded revision
  // string, so this schema follows `spec/m/` when the vendored pin moves.
  const idOf = (text: string): string => {
    const id = /^!!id:"([^"]+)"/u.exec(text)?.[1];
    if (id === undefined) throw new Error('a bundled schema carries no readable !!id');
    return id;
  };

  const USER_SCHEMA = `!!id:"https://example.com/reading.tn"
!!meta:"${idOf(META_TN)}"
!!import:"${idOf(CORE_TN)}"
{
  reading => {
    label: text
  }
}
`;

  it('registers all three, so a user schema resolves with no SchemaSource at all', () => {
    // The whole gap this closes: before it, a fresh Tson had an empty registry and this threw for
    // an unregistered !!meta. Note there is no `preload` and no source -- nothing fetches.
    const tson = standardLibrary();
    expect(() => tson.resolveSchema(USER_SCHEMA)).not.toThrow();
  });

  it('compiles what it resolves, end to end', () => {
    const tson = standardLibrary();
    const compiled = tson.compile(tson.resolveSchema(USER_SCHEMA));
    const value = tson.readTree(new TextEncoder().encode('{ label: "north ridge" }'), {
      schema: compiled,
      root: 'reading',
    });
    expect(value).toMatchObject({ kind: 'record', typeRef: 'reading' });
  });

  it('hands back a distinct registry each call, never a shared singleton', () => {
    // A registry is mutable state. Two callers sharing one would see each other's registrations,
    // and a test registering a schema would leak into the next.
    const first = standardLibrary();
    const second = standardLibrary();
    first.resolveSchema(USER_SCHEMA);
    expect(first).not.toBe(second);
    // `second` never saw the user schema, so resolving it there is still a first registration.
    expect(() => second.resolveSchema(USER_SCHEMA)).not.toThrow();
  });

  it('registerStandardLibrary returns the same instance it was given, for chaining', () => {
    const tson = createTson({});
    expect(registerStandardLibrary(tson)).toBe(tson);
  });
});
